### ISSUE TITLE
Trouble Downloading/Installing Caddy on Amazon Linux 2023 (AL2023) `"It wasn't possible to enable this project."`

### ISSUE THREAD

**Issue by timendez** [caddyserver/dist#119]
When running the following commands from [these docs](https://caddyserver.com/docs/install#fedora-redhat-centos):
```
sudo dnf install 'dnf-command(copr)'
```
results in
```
Last metadata expiration check: 0:17:43 ago on Wed Apr 24 20:36:06 2024.
Package dnf-plugins-core-4.3.0-13.amzn2023.0.4.noarch is already installed.
```
so that one worked.

Next up:
```
sudo dnf copr enable @caddy/caddy -y
```
results in
```
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.
Error: It wasn't possible to enable this project.
Repository 'epel-2023-x86_64' does not exist in project '@caddy/caddy'.
Available repositories: 'epel-8-aarch64', 'fedora-40-x86_64', 'fedora-38-x86_64', 'fedora-39-x86_64', 'fedora-39-aarch64', 'opensuse-tumbleweed-x86_64', 'fedora-40-aarch64', 'opensuse-leap-15.4-x86_64', 'epel-9-x86_64', 'opensuse-leap-15.5-aarch64', 'fedora-rawhide-x86_64', 'epel-7-x86_64', 'opensuse-tumbleweed-aarch64', 'opensuse-leap-15.5-x86_64', 'epel-8-x86_64', 'epel-9-aarch64', 'opensuse-leap-15.4-aarch64', 'fedora-rawhide-aarch64', 'fedora-38-aarch64'

If you want to enable a non-default repository, use the following command:
  'dnf copr enable @caddy/caddy <repository>'
But note that the installed repo file will likely need a manual modification.
```

Any suggestions on getting this set up?

Thank you!

**Comment by mohammed90** [comment]
@carlwgeorge, any clue?

**Comment by francislavoie** [comment]
Or @Conan-Kudo

**Comment by timendez** [comment]
No rush on this, I ended up needing https://github.com/mholt/caddy-ratelimit so I'm building with xcaddy

**Comment by carlwgeorge** [comment]
It's explained right there in your error message.

```
Repository 'epel-2023-x86_64' does not exist in project '@caddy/caddy'.
Available repositories: 'epel-8-aarch64', 'fedora-40-x86_64', 'fedora-38-x86_64', 'fedora-39-x86_64', 'fedora-39-aarch64', 'opensuse-tumbleweed-x86_64', 'fedora-40-aarch64', 'opensuse-leap-15.4-x86_64', 'epel-9-x86_64', 'opensuse-leap-15.5-aarch64', 'fedora-rawhide-x86_64', 'epel-7-x86_64', 'opensuse-tumbleweed-aarch64', 'opensuse-leap-15.5-x86_64', 'epel-8-x86_64', 'epel-9-aarch64', 'opensuse-leap-15.4-aarch64', 'fedora-rawhide-aarch64', 'fedora-38-aarch64'

If you want to enable a non-default repository, use the following command:
  'dnf copr enable @caddy/caddy <repository>'
```

The list of available repositories in that message corresponds to the list of active releases that are enabled for that copr.

https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/

Amazon Linux 2023 is not currently a platform that we target.  I don't use it myself and wouldn't feel comfortable being responsible for resolving any build errors on that platform, so my suggestion is that we need someone to get involved in the Caddy project to be responsible for builds for that platform.

I would also suggest that whoever that person is should submit a contribution to dnf to properly identify Amazon Linux in [this section of code](https://github.com/rpm-software-management/dnf-plugins-core/blob/4.7.0/plugins/copr.py#L457-L492), so that dnf on AL2023 asks for `amazonlinux-2023-x86_64` instead of `epel-2023-x86_64`.

**Comment by mholt** [comment]
Thanks @carlwgeorge !

**Comment by timendez** [comment]
Thanks for the explanation @carlwgeorge; is it recommended to avoid using Caddy on AL2023 because it's an unsupported distro, or as long as the build succeeds is it generally ok?

For what it's worth, the build with xcaddy worked fine, and Caddy is behaving as expected (for my limited reverse-proxy + rate-limiting setup)

cheers for the great project 🙇

**Comment by carlwgeorge** [comment]
I can't say for Caddy in general, but the copr should only be used with the distros listed in its active releases.

**Comment by mohammed90** [comment]
> Thanks for the explanation @carlwgeorge; is it recommended to avoid using Caddy on AL2023 because it's an unsupported distro, or as long as the build succeeds is it generally ok?
> 
> For what it's worth, the build with xcaddy worked fine, and Caddy is behaving as expected (for my limited reverse-proxy + rate-limiting setup)
> 
> cheers for the great project 🙇

The packages assume a distro because they execute a bunch of distro-specific operations during the installation & operation (e.g. systemd is present or not, config files placement, etc.). Beyond the packaging, it doesn't matter for Caddy what distro it's running on as long as the sysadmin sets it up properly on the system. Caddy assumes Linux, Windows, macOs as an umbrella.
