### ISSUE TITLE
Missing package for armv6 on the apt repository

### ISSUE THREAD

**Issue by mlcdf** [caddyserver/dist#62]
Hi,

I tried to install Caddy via `apt` on a Raspberry Pi 1+ according to the [official docs](https://caddyserver.com/docs/install#debian-ubuntu-raspbian). The install itself works, but the binary won't run because it doesn't match the architecture:

```
$ caddy --help
Illegal instruction
```

Same problem when downloading and installing by hand the [armhf](https://dl.cloudsmith.io/public/caddy/stable/deb/any-distro/pool/any-version/main/c/ca/caddy_2.4.0_linux_armv7.deb) package. Which is really weird, because `armhf` is the correct architecture according the dpkg (`dpkg --print-architecture` => `armhf`). And, the filename contains `armv7` which I also weird because I was certain that the Raspberry Pi 1 B+ was `armv6`.

So I went to GitHub release, downloaded and installed the `armv6` release and it worked !

```
$ caddy | head
Caddy is an extensible server platform.

usage:
  caddy <command> [<args...>]

commands:
  adapt           Adapts a configuration to Caddy's native JSON
  build-info      Prints information about this build
  environ         Prints the environment
  file-server     Spins up a production-ready file server
```

So I think the `armhf` should actually point to the armv6 package?

**Comment by francislavoie** [comment]
The problem is that from the debian repo perspective, `armv6` and `armv7` are both `armhf`. It's not possible for us to serve both, so we picked the newer one. Unfortunately, you happen to use a device which uses the older one.

https://github.com/caddyserver/caddy/blob/2aefe156869851a89d7a34e28c3e4ff3ac442fff/.github/workflows/release.yml#L146-L150

Best you can do is download the .deb directly from the GitHub releases (under the Assets accordion at the bottom of the notes), since we do still generate it, but don't upload it to CloudSmith.

https://github.com/caddyserver/caddy/releases/tag/v2.4.0

**Comment by mlcdf** [comment]
Hello Francis, 

Oh right, I see. Thank you very much for the explanation :)

**Comment by cinderblock** [comment]
In case anyone comes by here looking for the easy way to install the ARMv6 version of caddy:

1. Get the latest `.deb` file from releases
   - https://github.com/caddyserver/caddy/releases/download
2. Install it

#### Example

```bash
wget https://github.com/caddyserver/caddy/releases/download/v2.4.5/caddy_2.4.5_linux_armv6.deb
# Tell dpkg about it, will install if a different version is already installed
sudo dpkg -i caddy_2.4.5_linux_armv6.deb
# Only necessary if not yet installed
sudo apt-get install -y caddy
```
