### ISSUE TITLE
Add support for CentOS 9

### ISSUE THREAD

**Issue by waynon** [caddyserver/dist#80]
Currently, CentOS 9 Stream is not supported. Output of `dnf copr enable @caddy/caddy`:
```
Error: This repository does not have any builds yet so you cannot enable it now.
```

**Comment by carlwgeorge** [comment]
I've already done an EL9 compatible build.  I don't know why the `dnf copr` command is not working, there must be a bug in that dnf plugin.  In the meantime you can manually add the [repo definition](https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/repo/epel-9/group_caddy-caddy-epel-9.repo) to your `/etc/yum.repos.d/` directory and get access to the EL9 packages.

**Comment by carlwgeorge** [comment]
While asking about this in the `#fedora-buildsys` channel on Libera IRC, I was informed of another workaround instead of manually downloading the repo definition.  That command takes an optional chroot argument, so you can also run `dnf copr enable @caddy/caddy epel-9-$(arch)` to get the repo enable on C9S.  I am working on filing a bug report to get the behavior to match C8S, where it correctly picks the correct epel-8 chroot.

**Comment by carlwgeorge** [comment]
[Bug report filed](https://bugzilla.redhat.com/show_bug.cgi?id=2058471).
