### ISSUE TITLE
Caddy crashing with caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by kwe** [caddyserver/dist#99]
I've started getting the following...

```bash
sudo service caddy status
● caddy.service - Caddy
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2023-06-25 07:32:58 BST; 1h 18min ago
     Docs: https://caddyserver.com/docs/
  Process: 2096 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=2)
 Main PID: 2096 (code=exited, status=2)

Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]:         net/net.go:183 +0x45 fp=0xc0048dda98 sp=0xc0048dda50 pc=0x55b905
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]: net.(*TCPConn).Read(0xc0048ddb30?, {0xc0018d86c0?, 0xc00121f7a0?, 0x18?})
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]:         <autogenerated>:1 +0x29 fp=0xc0048ddac8 sp=0xc0048dda98 pc=0x56e029
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]: crypto/tls.(*atLeastReader).Read(0xc00121f7a0, {0xc0018d86c0?, 0xc00121f7a0?, 0x0?})
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]:         crypto/tls/conn.go:788 +0x3d fp=0xc0048ddb10 sp=0xc0048ddac8 pc=0x6c369d
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]: bytes.(*Buffer).ReadFrom(0xc002ac5790, {0x1ddc440, 0xc00121f7a0})
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]:         bytes/buffer.go:202 +0x98 fp=0xc0048ddb68 sp=0xc0048ddb10 pc=0x510798
Jun 25 07:32:52 www.sitenameremoved.co.uk caddy[2096]: crypto/tls.(*Conn).readFromUntil(0xc002ac5500, {0x1de1e60?, 0xc000624280}, 0x0?)
Jun 25 07:32:58 www.sitenameremoved.co.uk systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 25 07:32:58 www.sitenameremoved.co.uk systemd[1]: caddy.service: Failed with result 'exit-code'.
```
server is running 
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

Any advice on how I can debug?

**Comment by kwe** [comment]
I should add that Caddy has been working fine for months prior to this and a restart works, so far two of these crashes in the last week.

**Comment by francislavoie** [comment]
Those logs are truncated. Please show your full logs with the command documented here https://caddyserver.com/docs/running#using-the-service

**Comment by kwe** [comment]
thank you so much for the tip...
The full logs point to a..

```bash
runtime: failed to create new OS thread (have 513 already; errno=11
runtime: may need to increase max user processes (ulimit -u)
```

Which starts all the crashing.
Many thanks again.

**Comment by mholt** [comment]
I'm not sure this was closed intentionally, so...

Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>
